openapi: 3.0.2
info:
    title: New API
    version: 0.0.1
    description: API for chat assistant. OpenAI compatible.
paths:
    /chat/completions:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/chat_completion_request'
                required: true
            tags:
                - chat
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/chat_completion_response'
                    description: OK
                '422':
                    description: Unprocessable Entity
                '500':
                    description: Something somewhere went terribly wrong.
            operationId: chat_completions
components:
    schemas:
        chat_completion_request:
            description: ''
            required:
                - model
                - messages
            type: object
            properties:
                model:
                    description: ''
                    type: string
                messages:
                    description: ''
                    type: array
                    items:
                        $ref: '#/components/schemas/chat_completion_messages'
        chat_completion_messages:
            description: ''
            required:
                - role
                - content
            type: object
            properties:
                role:
                    description: ''
                    type: string
                content:
                    description: ''
                    type: string
        chat_completion_response:
            description: ''
            required:
                - id
                - model
                - created
                - object
                - choices
            type: object
            properties:
                id:
                    description: ''
                    type: string
                model:
                    description: ''
                    type: string
                created:
                    description: ''
                    type: integer
                object:
                    description: chat.completion
                    type: string
                service_tier:
                    description: default
                    type: string
                system_fingerprint:
                    description: ''
                    type: string
                choices:
                    description: ''
                    type: array
                    items:
                        $ref: '#/components/schemas/chat_completion_choice'
        chat_completion_choice:
            description: ''
            required:
                - index
                - message
                - finish_reason
            type: object
            properties:
                index:
                    description: ''
                    type: integer
                message:
                    $ref: '#/components/schemas/chat_completion_choice_message'
                    description: ''
                finish_reason:
                    description: stop
                    type: string
        chat_completion_choice_message:
            description: ''
            required:
                - role
                - content
            type: object
            properties:
                role:
                    description: ''
                    type: string
                content:
                    description: ''
                    type: string
                refusal:
                    description: ''
                    type: string
