# coding: utf-8

"""
    Assistant API

    A modular chat assistant.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import os
import sys

from fastapi import FastAPI

file_dir = os.path.dirname(__file__)
sys.path.append(file_dir)

from assistant.apis.assistant_api import router as AssistantApiRouter
from assistant.assistant_container import configure

app = FastAPI(
    title="Assistant API",
    description="A modular chat assistant.",
    version="1.0.0",
)

app.include_router(AssistantApiRouter)
configure()
