# coding: utf-8

"""
    OpenAI API

    The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

    The version of the OpenAPI document: 2.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from assistant.apis.chat_api import router as ChatApiRouter
from assistant.apis.models_api import router as ModelsApiRouter
from assistant_container import configure

app = FastAPI(
    title="OpenAI API",
    description="The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.",
    version="2.3.0",
)


app.include_router(ChatApiRouter)
app.include_router(ModelsApiRouter)


configure()
