{{- if .Values.assistant.egress.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "chat-assistant.fullname" . }}-assistant-egress
  labels:
    {{- include "assistant.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chat-assistant.name" . }}
      component: assistant
  policyTypes:
  - Egress
  egress:
  {{- range .Values.assistant.egress.rules }}
  - {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}