apiVersion: v1
kind: Service
metadata:  
  name: assistant
spec:  
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: assistant
  sessionAffinity: None
  type: ClusterIP