apiVersion: apps/v1
kind: Deployment
metadata:
  name: assistant
  labels:
    app: assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assistant
  template:
    metadata:
      labels:
        app: assistant
    spec:
      imagePullSecrets:
      - name: "pull-secret"
      volumes: 
      - name: mcp-config-volume
        configMap:
          name: assistant-mcp-cm
      - name: subagents-config-volume
        configMap:
          name: assistant-subagents-cm
      containers:
      - name: assistant
        image: {{ .Values.assistant.image.repository }}:{{ .Values.assistant.image.tag }}
        imagePullPolicy: {{ .Values.assistant.image.pullPolicy }}
        volumeMounts:
          - name: mcp-config-volume
            mountPath: /config/mcp
          - name: subagents-config-volume
            mountPath: /config/subagents
        envFrom:
          - configMapRef:
              name: assistant-cm
          - secretRef:
              name: assistant-secret
        ports:
        - containerPort: 8080
        command:
          - "uv"
          - "run"
        args:
          {{- if .Values.assistant.debug }}
          {{- range $arg :=  .Values.assistant.debugArgs }}
          - {{ $arg | quote -}}
          {{ end }}
          {{- else }}
          {{- range $arg :=  .Values.assistant.args }}
          - {{ $arg | quote -}}
          {{ end }}
          {{- end }}
---
{{- include "egressNetworkPolicy" (dict "enabled" .Values.assistant.egress.enabled "allowedHosts" .Values.assistant.egress.allowedHosts "chartName" "assistant" "podSelectorLabels" (dict "app" "assistant")) }}