apiVersion: v1
kind: ConfigMap
metadata:
  name: assistant-cm
data:
  SETTINGS_MCP_SERVERS: |
    {{ toJson .Values.mcpServers }}
  SETTINGS_PROMPTS_REPHRASE_QUESTION_PROMPT: |
{{ .Values.assistant.settings.prompt.SETTINGS_PROMPTS_REPHRASE_QUESTION_PROMPT |indent 6 }}
  SETTINGS_PROMPTS_REPHRASE_ANSWER_PROMPT: |
{{ .Values.assistant.settings.prompt.SETTINGS_PROMPTS_REPHRASE_ANSWER_PROMPT |indent 6 }}