apiVersion: v1
kind: Service
metadata:  
  name: evidently  
spec:  
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: evidently
  sessionAffinity: None
  type: ClusterIP
