apiVersion: v1
kind: Service
metadata:  
  name: home-assistant-component
spec:  
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: home-assistant-component
  sessionAffinity: None
  type: ClusterIP