{{- range $server :=  .Values.mcpServers.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $server.name }}
  labels:
    app: {{ $server.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $server.name }}
  template:
    metadata:
      labels:
        app: {{ $server.name }}
    spec:
      imagePullSecrets:
      - name: "pull-secret"
      containers:
      - name: {{ $server.name }}
        imagePullPolicy: Always
        {{- if $server.command }}
        command: {{ $server.command | toJson }}
        {{- end }}
        envFrom:
          - configMapRef:
              name: {{ $server.name }}
          - secretRef:
              name: {{ $server.name }}     
        image:  {{ $server.image }}
        ports:
        - containerPort: {{ $server.port }}
{{ end }}