{{- range $server :=  .Values.mcpServers.deployments }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $server.name }}
data:
  {{- range $key, $value := $server.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{ end }}
