{{- range $deploy :=  .Values.components.rag }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploy.name }}
  labels:
    app: {{ $deploy.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $deploy.name }}
  template:
    metadata:
      labels:
        app: {{ $deploy.name }}
    spec:
      imagePullSecrets:
      - name: "pull-secret"
      containers:
      - name: {{ $deploy.name }}
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: {{ $deploy.name }}-llm
          - configMapRef:
              name: {{ $deploy.name }}-ollama
          - configMapRef:
              name: {{ $deploy.name }}-qdrant
        image: ghcr.io/melvinkl/chat_assistant/rag:latest
        ports:
        - containerPort: 8080
        command: 
          - "poetry"
          - "run"
        args:
          {{- if $deploy.debug }}
          {{- range $arg :=  $deploy.debugArgs }}
          - {{ $arg | quote -}}
          {{ end }}
          {{- else }}
          {{- range $arg :=  $deploy.args }}
          - {{ $arg | quote -}}
          {{ end }}
          {{- end }}
{{ end }}          