{{- range $deploy :=  .Values.components.rag }}
{{- if $deploy.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/whitelist-source-range: 192.168.0.1/16
    cert-manager.io/cluster-issuer: cert-issuer
    kubernetes.io/tls-acme: "true"
  name: {{ $deploy.name }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ $deploy.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ $deploy.name }}
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ $deploy.ingress.host }}
    secretName: tls-certificate
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-certificate
spec:
  dnsNames:
    - {{ $deploy.ingress.host }}    
  secretName: tls-certificate
  issuerRef:
    name: cert-issuer
    kind: ClusterIssuer    
{{- end }}
{{ end }}          