# coding: utf-8

"""
OpenAI API

The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

The version of the OpenAPI document: 2.3.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum


try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class AssistantSupportedModels(str, Enum):
    """
    AssistantSupportedModels
    """

    """
    allowed enum values
    """
    O3_MINUS_MINI = "o3-mini"
    O3_MINUS_MINI_MINUS_2025_MINUS_01_MINUS_31 = "o3-mini-2025-01-31"
    O1 = "o1"
    O1_MINUS_2024_MINUS_12_MINUS_17 = "o1-2024-12-17"
    GPT_MINUS_4O = "gpt-4o"
    GPT_MINUS_4O_MINUS_2024_MINUS_11_MINUS_20 = "gpt-4o-2024-11-20"
    GPT_MINUS_4O_MINUS_2024_MINUS_08_MINUS_06 = "gpt-4o-2024-08-06"
    GPT_MINUS_4O_MINUS_2024_MINUS_05_MINUS_13 = "gpt-4o-2024-05-13"
    GPT_MINUS_4O_MINUS_MINI = "gpt-4o-mini"
    GPT_MINUS_4O_MINUS_MINI_MINUS_2024_MINUS_07_MINUS_18 = "gpt-4o-mini-2024-07-18"
    GPT_MINUS_4_PERIOD_5_MINUS_PREVIEW = "gpt-4.5-preview"
    GPT_MINUS_4_PERIOD_5_MINUS_PREVIEW_MINUS_2025_MINUS_02_MINUS_27 = "gpt-4.5-preview-2025-02-27"
    GPT_MINUS_4_MINUS_TURBO = "gpt-4-turbo"
    GPT_MINUS_4_MINUS_TURBO_MINUS_2024_MINUS_04_MINUS_09 = "gpt-4-turbo-2024-04-09"
    GPT_MINUS_4_MINUS_0125_MINUS_PREVIEW = "gpt-4-0125-preview"
    GPT_MINUS_4_MINUS_TURBO_MINUS_PREVIEW = "gpt-4-turbo-preview"
    GPT_MINUS_4_MINUS_1106_MINUS_PREVIEW = "gpt-4-1106-preview"
    GPT_MINUS_4_MINUS_VISION_MINUS_PREVIEW = "gpt-4-vision-preview"
    GPT_MINUS_4 = "gpt-4"
    GPT_MINUS_4_MINUS_0314 = "gpt-4-0314"
    GPT_MINUS_4_MINUS_0613 = "gpt-4-0613"
    GPT_MINUS_4_MINUS_32K = "gpt-4-32k"
    GPT_MINUS_4_MINUS_32K_MINUS_0314 = "gpt-4-32k-0314"
    GPT_MINUS_4_MINUS_32K_MINUS_0613 = "gpt-4-32k-0613"
    GPT_MINUS_3_PERIOD_5_MINUS_TURBO = "gpt-3.5-turbo"
    GPT_MINUS_3_PERIOD_5_MINUS_TURBO_MINUS_16K = "gpt-3.5-turbo-16k"
    GPT_MINUS_3_PERIOD_5_MINUS_TURBO_MINUS_0613 = "gpt-3.5-turbo-0613"
    GPT_MINUS_3_PERIOD_5_MINUS_TURBO_MINUS_1106 = "gpt-3.5-turbo-1106"
    GPT_MINUS_3_PERIOD_5_MINUS_TURBO_MINUS_0125 = "gpt-3.5-turbo-0125"
    GPT_MINUS_3_PERIOD_5_MINUS_TURBO_MINUS_16K_MINUS_0613 = "gpt-3.5-turbo-16k-0613"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AssistantSupportedModels from a JSON string"""
        return cls(json.loads(json_str))
