# coding: utf-8

"""
    OpenAI API

    The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

    The version of the OpenAPI document: 2.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from assistant.models.computer_action import ComputerAction
from assistant.models.computer_tool_call_safety_check import ComputerToolCallSafetyCheck
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ComputerToolCall(BaseModel):
    """
    A tool call to a computer use tool. See the  [computer use guide](/docs/guides/tools-computer-use) for more information. 
    """ # noqa: E501
    type: StrictStr = Field(description="The type of the computer call. Always `computer_call`.")
    id: StrictStr = Field(description="The unique ID of the computer call.")
    call_id: StrictStr = Field(description="An identifier used when responding to the tool call with output. ")
    action: ComputerAction
    pending_safety_checks: List[ComputerToolCallSafetyCheck] = Field(description="The pending safety checks for the computer call. ")
    status: StrictStr = Field(description="The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API. ")
    __properties: ClassVar[List[str]] = ["type", "id", "call_id", "action", "pending_safety_checks", "status"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('computer_call',):
            raise ValueError("must be one of enum values ('computer_call')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('in_progress', 'completed', 'incomplete',):
            raise ValueError("must be one of enum values ('in_progress', 'completed', 'incomplete')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ComputerToolCall from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of action
        if self.action:
            _dict['action'] = self.action.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in pending_safety_checks (list)
        _items = []
        if self.pending_safety_checks:
            for _item in self.pending_safety_checks:
                if _item:
                    _items.append(_item.to_dict())
            _dict['pending_safety_checks'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ComputerToolCall from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type") if obj.get("type") is not None else 'computer_call',
            "id": obj.get("id"),
            "call_id": obj.get("call_id"),
            "action": ComputerAction.from_dict(obj.get("action")) if obj.get("action") is not None else None,
            "pending_safety_checks": [ComputerToolCallSafetyCheck.from_dict(_item) for _item in obj.get("pending_safety_checks")] if obj.get("pending_safety_checks") is not None else None,
            "status": obj.get("status")
        })
        return _obj


