# coding: utf-8

"""
OpenAI API

The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

The version of the OpenAPI document: 2.3.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field, StrictStr

from assistant.models.log_prob_properties import LogProbProperties

try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class CreateTranscriptionResponseJson(BaseModel):
    """
    Represents a transcription response returned by model, based on the provided input.
    """  # noqa: E501

    text: StrictStr = Field(description="The transcribed text.")
    logprobs: Optional[List[LogProbProperties]] = Field(
        default=None,
        description="The log probabilities of the tokens in the transcription. Only returned with the models `gpt-4o-transcribe` and `gpt-4o-mini-transcribe` if `logprobs` is added to the `include` array. ",
    )
    __properties: ClassVar[List[str]] = ["text", "logprobs"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CreateTranscriptionResponseJson from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={},
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in logprobs (list)
        _items = []
        if self.logprobs:
            for _item in self.logprobs:
                if _item:
                    _items.append(_item.to_dict())
            _dict["logprobs"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CreateTranscriptionResponseJson from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "text": obj.get("text"),
                "logprobs": (
                    [LogProbProperties.from_dict(_item) for _item in obj.get("logprobs")]
                    if obj.get("logprobs") is not None
                    else None
                ),
            }
        )
        return _obj
