# coding: utf-8

"""
OpenAI API

The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

The version of the OpenAPI document: 2.3.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum


try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class FileSearchRanker(str, Enum):
    """
    The ranker to use for the file search. If not specified will use the `auto` ranker.
    """

    """
    allowed enum values
    """
    AUTO = "auto"
    DEFAULT_2024_08_21 = "default_2024_08_21"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FileSearchRanker from a JSON string"""
        return cls(json.loads(json_str))
