# coding: utf-8

"""
OpenAI API

The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

The version of the OpenAPI document: 2.3.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional

try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class FunctionToolCallResource(BaseModel):
    """
    FunctionToolCallResource
    """  # noqa: E501

    id: StrictStr = Field(description="The unique ID of the function tool call. ")
    type: StrictStr = Field(description="The type of the function tool call. Always `function_call`. ")
    call_id: StrictStr = Field(description="The unique ID of the function tool call generated by the model. ")
    name: StrictStr = Field(description="The name of the function to run. ")
    arguments: StrictStr = Field(description="A JSON string of the arguments to pass to the function. ")
    status: Optional[StrictStr] = Field(
        default=None,
        description="The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API. ",
    )
    __properties: ClassVar[List[str]] = ["id", "type", "call_id", "name", "arguments", "status"]

    @field_validator("type")
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ("function_call",):
            raise ValueError("must be one of enum values ('function_call')")
        return value

    @field_validator("status")
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in (
            "in_progress",
            "completed",
            "incomplete",
        ):
            raise ValueError("must be one of enum values ('in_progress', 'completed', 'incomplete')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FunctionToolCallResource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={},
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of FunctionToolCallResource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "type": obj.get("type"),
                "call_id": obj.get("call_id"),
                "name": obj.get("name"),
                "arguments": obj.get("arguments"),
                "status": obj.get("status"),
            }
        )
        return _obj
