# coding: utf-8

"""
OpenAI API

The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

The version of the OpenAPI document: 2.3.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from enum import Enum

try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class Includable(str, Enum):
    """
    Specify additional output data to include in the model response. Currently supported values are: - `file_search_call.results`: Include the search results of   the file search tool call. - `message.input_image.image_url`: Include image urls from the input message. - `computer_call_output.output.image_url`: Include image urls from the computer call output.
    """

    """
    allowed enum values
    """
    FILE_SEARCH_CALL_PERIOD_RESULTS = "file_search_call.results"
    MESSAGE_PERIOD_INPUT_IMAGE_PERIOD_IMAGE_URL = "message.input_image.image_url"
    COMPUTER_CALL_OUTPUT_PERIOD_OUTPUT_PERIOD_IMAGE_URL = "computer_call_output.output.image_url"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Includable from a JSON string"""
        return cls(json.loads(json_str))
