# coding: utf-8

"""
OpenAI API

The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

The version of the OpenAPI document: 2.3.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from inspect import getfullargspec
from typing import TYPE_CHECKING, Any, Dict, List, Optional, Union

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictStr,
    ValidationError,
    field_validator,
)
from typing_extensions import Literal

from assistant.models.easy_input_message import EasyInputMessage
from assistant.models.item_reference import ItemReference

try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

INPUTITEM_ONE_OF_SCHEMAS = ["EasyInputMessage", "Item", "ItemReference"]


class InputItem(BaseModel):
    """
    InputItem
    """

    # data type: EasyInputMessage
    oneof_schema_1_validator: Optional[EasyInputMessage] = None
    # data type: Item
    oneof_schema_2_validator: Optional[Dict[str, Any]] = None
    # data type: ItemReference
    oneof_schema_3_validator: Optional[ItemReference] = None
    actual_instance: Optional[Union[EasyInputMessage, Item, ItemReference]] = None
    one_of_schemas: List[str] = Literal["EasyInputMessage", "Item", "ItemReference"]

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    discriminator_value_class_map: Dict[str, str] = {}

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator("actual_instance")
    def actual_instance_must_validate_oneof(cls, v):
        instance = InputItem.model_construct()
        error_messages = []
        match = 0
        # validate data type: EasyInputMessage
        if not isinstance(v, EasyInputMessage):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EasyInputMessage`")
        else:
            match += 1
        # validate data type: Item
        if not isinstance(v, Item):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Item`")
        else:
            match += 1
        # validate data type: ItemReference
        if not isinstance(v, ItemReference):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ItemReference`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when setting `actual_instance` in InputItem with oneOf schemas: EasyInputMessage, Item, ItemReference. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when setting `actual_instance` in InputItem with oneOf schemas: EasyInputMessage, Item, ItemReference. Details: "
                + ", ".join(error_messages)
            )
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into EasyInputMessage
        try:
            instance.actual_instance = EasyInputMessage.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Item
        try:
            instance.actual_instance = Item.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ItemReference
        try:
            instance.actual_instance = ItemReference.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when deserializing the JSON string into InputItem with oneOf schemas: EasyInputMessage, Item, ItemReference. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when deserializing the JSON string into InputItem with oneOf schemas: EasyInputMessage, Item, ItemReference. Details: "
                + ", ".join(error_messages)
            )
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())
