# coding: utf-8

"""
OpenAI API

The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

The version of the OpenAPI document: 2.3.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from enum import Enum

try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class ToolChoiceOptions(str, Enum):
    """
    Controls which (if any) tool is called by the model.  `none` means the model will not call any tool and instead generates a message.  `auto` means the model can pick between generating a message or calling one or more tools.  `required` means the model must call one or more tools.
    """

    """
    allowed enum values
    """
    NONE = "none"
    AUTO = "auto"
    REQUIRED = "required"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ToolChoiceOptions from a JSON string"""
        return cls(json.loads(json_str))
