# coding: utf-8

"""
    Component API

    API for integrating components into the Assistant

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI
from dependency_injector.containers import DeclarativeContainer
from tracely import init_tracing
from tracely import trace_event

from base_component_api.apis.component_api import router as ComponentApiRouter
from base_component_api.dependency_container import DependencyContainer

init_tracing(
    address="http://evidently:8000",
    # api_key=”YOUR_EVIDENTLY_TOKEN”,
    project_id="0193ce87-92b2-7c6c-a429-b414d9710b5d",
    export_name="chat_assistant",
)

container = DependencyContainer()
app = FastAPI(
    title="Component API",
    description="API for integrating components into the Assistant",
    version="1.0.0",
)
app.container = container
app.include_router(ComponentApiRouter)


def dependency_override(new_container: DeclarativeContainer):
    app.container.override(new_container)
