# coding: utf-8

"""
    Component API

    API for integrating components into the Assistant

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from base_component_api.apis.component_api import router as ComponentApiRouter
from base_component_api.dependency_container import configure
from fastapi import FastAPI

configure()

app = FastAPI(
    title="Component API",
    description="API for integrating components into the Assistant",
    version="1.0.0",
)
app.include_router(ComponentApiRouter)
