# coding: utf-8

"""
    Component API

    API for integrating components into the Assistant

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from assistant.component_api.api.component_api import ComponentApi


class TestComponentApi(unittest.TestCase):
    """ComponentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ComponentApi()

    def tearDown(self) -> None:
        pass

    def test_act(self) -> None:
        """Test case for act

        """
        pass

    def test_answer_question(self) -> None:
        """Test case for answer_question

        """
        pass

    def test_get_available_actions(self) -> None:
        """Test case for get_available_actions

        """
        pass

    def test_upload_document(self) -> None:
        """Test case for upload_document

        """
        pass


if __name__ == '__main__':
    unittest.main()
