# coding: utf-8

"""
    Component API

    API for integrating components into the Assistant

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from assistant.component_api.models.chat_response import ChatResponse


class TestChatResponse(unittest.TestCase):
    """ChatResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChatResponse:
        """Test ChatResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ChatResponse`
        """
        model = ChatResponse()
        if include_optional:
            return ChatResponse(
                sources = [
                    {"Metadata":[{"Value":"Value","Name":"Name"},{"Value":"Value","Name":"Name"}],"page_content":"page_content"}
                    ],
                answer = ''
            )
        else:
            return ChatResponse(
                sources = [
                    {"Metadata":[{"Value":"Value","Name":"Name"},{"Value":"Value","Name":"Name"}],"page_content":"page_content"}
                    ],
                answer = '',
        )
        """

    def testChatResponse(self):
        """Test ChatResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
