# coding: utf-8

# flake8: noqa

"""
    Component API

    API for integrating components into the Assistant

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from assistant.component_api.api.component_api import ComponentApi
from assistant.component_api.api_client import ApiClient

# import ApiClient
from assistant.component_api.api_response import ApiResponse
from assistant.component_api.configuration import Configuration
from assistant.component_api.exceptions import (
    ApiAttributeError,
    ApiException,
    ApiKeyError,
    ApiTypeError,
    ApiValueError,
    OpenApiException,
)

# import models into sdk package
from assistant.component_api.models.chat_response import ChatResponse
from assistant.component_api.models.description import Description
from assistant.component_api.models.key_value import KeyValue
from assistant.component_api.models.source_document import SourceDocument
