name: Docker Image CI

on:
  workflow_dispatch:
  release:
    types: [published]  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push Docker image
        run: |
          export TAG=ghcr.io/${GITHUB_REPOSITORY@L}/assistant:${{ github.event.release.tag_name }}
          export LATEST_TAG=ghcr.io/${GITHUB_REPOSITORY@L}/assistant:latest
          docker build . -f assistant/Dockerfile -t $TAG
          docker push $TAG
          docker image tag $TAG $LATEST_TAG 
          docker push $LATEST_TAG
